### ISSUE TITLE
Quality 

### ISSUE THREAD

**Issue by guitiba05** [Michele0303/TikTok-Live-Recorder#51]
does the script downloads the live in source quality?

**Comment by aCS6** [comment]
Thank you for reaching out! I appreciate your question, but I'm afraid I'm not entirely clear on what you mean by 'source quality.' Could you please provide more context or clarify your question? This will help me better understand your concern and provide you with an accurate response. I'm here to assist you further!

**Comment by booleangit** [comment]
> does the script downloads the live in source quality?
> 
> 

It does. However, if you use the -ffmpeg option, it will produce a larger file with lower quality. This is because the dev used the transcode parameter instead of just "-c copy". If he fixes that, you've got the best tool available.

So in the meantime just convert the stream manually afterwards using ffmpeg; it will only take a few seconds.
