### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by YesYesTheDev** [Michele0303/tiktok-live-recorder#85]
Possibly create a discord bot where you can request multiple streams to be recorded to

**Comment by sotero1113** [comment]
> Possibly create a discord bot where you can request multiple streams to be recorded to

yea its possible, currently i broken the code up into microservices and hosted it on google cloud so that it can run 24/7 and record as many users streams as i want. 

But for discord bots, you will need to look into how to first create a discord bot using a tutorial or documents, from my understanding you will need to host that bot somewhere. Then you will listen for commands that are sent on a discord channel(ie tiktok username) and send that to your recording service
